We create seed file in ./installer_hooks/20-postcopy-user as installer always runs with root permissions:

diff --git a/installer_hooks/20-postcopy-user b/installer_hooks/20-postcopy-user
--- a/installer_hooks/20-postcopy-user
+++ b/installer_hooks/20-postcopy-user
@@ -37,6 +37,37 @@ if [ -f "$TARGETDIR/conf/users.dat" ]; then
 		execPrint chmod g+rw $TARGETDIR/conf/users.dat
 fi
 
+
+
+# encryption of secrets
+SEED_DIR='/usr/local/etc/opmantek';
+SEED_FILE="$SEED_DIR/seed.txt";
+
+# Only if seed file does not yet exist:
+if [ ! -e "${SEED_FILE}" ]; then
+	if [ ! -e "${SEED_DIR}" ]; then
+		execPrint "mkdir -p ${SEED_DIR}";
+	fi;
+	execPrint "chmod 0770 ${SEED_DIR}";
+	execPrint "chown ${WEBGRP}:nmis ${SEED_DIR}";
+
+	# OMK-8690: OMK::Common::_make_seed() function is the basis of this perl code:
+	SEEDLENGTH=256;
+
+	SEED="$(perl -e 'use strict;use warnings;use diagnostics;my $seedlength='"${SEEDLENGTH}"';my @charset=(("A".."Z"),("a".."z"),(0..9));my $range=$#charset+1;my $seed;for(1..$seedlength){$seed .= $charset[int(rand($range))];};if(length($seed)!=$seedlength){die "seed length of ".length($seed)." not equal to $seedlength characters. Aborting ...\n";$seed="";exit 1;};print "$seed\n";' 2>&1)";
+	# Make sure we have the correct length seed before writing it:
+	if [ "${#SEED}" != "${SEEDLENGTH}" ]; then
+		echo "seed length ${#SEED} incorrect. Aborting ...";
+		exit 1;
+	fi;
+	# Write seed and set owner, group and permissions:
+	execPrint "echo ${SEED} > ${SEED_FILE}";
+	execPrint "chown ${WEBGRP}:nmis ${SEED_FILE}";
+	execPrint "chmod 0440 ${SEED_FILE}";
+fi;
+
+
+
 exit 0
 
 
