RHEL installer: install gcc early
cpanm packages installed early require gcc

diff --git a/installer_hooks/30-pre-dependencies b/installer_hooks/30-pre-dependencies
--- a/installer_hooks/30-pre-dependencies
+++ b/installer_hooks/30-pre-dependencies
@@ -189,12 +189,13 @@ if [ "${OSFLAVOUR}" = "redhat" ]; then
             printBanner "Some required packages need to be installed first!"
             echo "$PRODUCT requires the following packages to be installed first:";
             echo
-            echo "perl-CPAN perl-App-cpanminus using $MGR";
+            echo "gcc perl-CPAN perl-App-cpanminus using $MGR";
             echo "Devel::GlobalDestruction::XS Proc::Queue Net::SMTPS using CPANM"
             echo "The installer can download and install these packages.";
             if input_yn "Do you want to install these packages now?" "5af4"; then
                 REPO='';
                 NEEDREPO='';
+				install_package "gcc"||:;  #cpan packages below use this, fails without making sure this isn't installed
                 install_package "perl-CPAN"||:;
                 install_package "perl-App-cpanminus"||:;
                 install_package "perl-LWP-Protocol-https"||:;
