OMK-9686 - NMIS install now works on Debian 10, Debian 11, and Ubuntu 22.04

diff --git a/installer_hooks/30-pre-dependencies b/installer_hooks/30-pre-dependencies
--- a/installer_hooks/30-pre-dependencies
+++ b/installer_hooks/30-pre-dependencies
@@ -126,25 +126,33 @@ fi
 
 if [ "$CANUSEWEB" = 1 ]; then
 	if { [ "${OSFLAVOUR}" = "ubuntu" ] && [ "${OS_MAJOR}" -ge 19 ]; }; then
+		printBanner "Checking if 'libssl1.1' is installed..."
 		# FIX FOR UBUNTU >= 19.00 WHICH REQUIRES libssl1.0.0 WHEN INSTALLING MONGODB:
 		# prime_apt is called during  install_package() and after disable_distro() functions:
-		NEEDDISTRO="bionic";
-		# this function calls enable_distro
-		install_package "libssl1.0.0";
+#		NEEDDISTRO="bionic";
+#		# this function calls enable_distro
+		haveit=`apt -qq list --installed libssl1.1 2>/dev/null`
+		if [ -z "$haveit" ]; then
+			echolog "Installing 'libssl1.1'"
+			execPrint dpkg -i installer_hooks/libraries/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
+		else
+			echolog "'libssl1.1' is already installed."
+		fi;
+		unset haveit
 		# clean up as this was temporary
-		disable_distro "${NEEDDISTRO}";
-	elif [ "${OSFLAVOUR}" = "debian" ] && [ "${OS_MAJOR}" -ge 10 ]; then
-		# FIX FOR DEBIAN >= 10 WHICH REQUIRES libssl1.0.0 AND jessie GPG PUBKEY WHEN INSTALLING MONGODB:
-		# prime_apt is called during  install_package() and after disable_distro() functions:
-		NEEDDISTRO="jessie";
-		# get the release key first
-		type wget >/dev/null 2>&1 && GIMMEKEY="wget --tries=5 -q -T 20 -O - https://ftp-master.debian.org/keys/archive-key-8.asc" || GIMMEKEY="curl --retry 4 -L -s -m 20 https://ftp-master.debian.org/keys/archive-key-8.asc";
-		# apt-key adv doesn't work cleanly with gpg 2.1+
-		execPrint "$GIMMEKEY | apt-key add -"||:;
-		# this function calls enable_distro
-		install_package "libssl1.0.0";
-		# clean up as this was temporary
-		disable_distro "${NEEDDISTRO}";
+#		disable_distro "${NEEDDISTRO}";
+#	elif [ "${OSFLAVOUR}" = "debian" ] && [ "${OS_MAJOR}" -ge 10 ]; then
+#		# FIX FOR DEBIAN >= 10 WHICH REQUIRES libssl1.0.0 AND jessie GPG PUBKEY WHEN INSTALLING MONGODB:
+#		# prime_apt is called during  install_package() and after disable_distro() functions:
+#		NEEDDISTRO="jessie";
+#		# get the release key first
+#		type wget >/dev/null 2>&1 && GIMMEKEY="wget --tries=5 -q -T 20 -O - https://ftp-master.debian.org/keys/archive-key-8.asc" || GIMMEKEY="curl --retry 4 -L -s -m 20 https://ftp-master.debian.org/keys/archive-key-8.asc";
+#		# apt-key adv doesn't work cleanly with gpg 2.1+
+#		execPrint "$GIMMEKEY | apt-key add -"||:;
+#		# this function calls enable_distro
+#		install_package "libssl1.0.0";
+#		# clean up as this was temporary
+#		disable_distro "${NEEDDISTRO}";
 	else
 		# default action where above fix not needed
 		[ "$OSFLAVOUR" = "redhat" ] && prime_yum
@@ -154,6 +162,7 @@ fi
 
 # check and get mongodb, returns 0 if ok, 1 or 2 otherwise
 # absolute min for nmis 9 is 3.4.0
+printBanner "Checking if mongoDB is installed..."
 mongo_or_bust 3 4 0 || exit 1
 
 
@@ -264,16 +273,16 @@ if ! check_missing_packages $PKGLIST; then
 								fi
 						elif [ "$OSFLAVOUR" = "debian" -a "$OS_MAJOR" -ge "9" ]; then
 								NEEDDISTRO=''
-								# librrd4 and libpng12-0 are only present up to jessie/8
-								if [ "$pkg" = "librrd4" -o "$pkg" = "libpng12-0" ]; then
-										NEEDDISTRO="jessie"
-								fi
+#								# librrd4 and libpng12-0 are only present up to jessie/8
+#								if [ "$pkg" = "librrd4" -o "$pkg" = "libpng12-0" ]; then
+#										NEEDDISTRO="jessie"
+#								fi
 						elif [ "$OSFLAVOUR" = "ubuntu" -a \( "$OS_MAJOR" -gt "16" -o \( "$OS_MAJOR" = "16" -a "$OS_MINOR" -gt "4" \) \) ] ; then
 								NEEDDISTRO=''
-								# librrd4 and libpng12-0 are only present up to xenial/16.04, NOT 16.10...
-								if [ "$pkg" = "librrd4" -o "$pkg" = "libpng12-0" ]; then
-										NEEDDISTRO="xenial"
-								fi
+#								# librrd4 and libpng12-0 are only present up to xenial/16.04, NOT 16.10...
+#								if [ "$pkg" = "librrd4" -o "$pkg" = "libpng12-0" ]; then
+#										NEEDDISTRO="xenial"
+#								fi
 						fi
 
 						install_package $pkg
